name: deploy on ghcr
run-name: tag-release

on: 
  push:
    tags:
      - 'v*'

jobs:
  deploy_delob_image_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_code
        uses: actions/checkout@v3

      - name: login_to_ghcr
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      
      - name: repository_name
        uses: ASzc/change-string-case-action@v2
        with:
            string: ${{ github.repository_owner }}

      - name: deploy_delob_image_to_ghcr
        run: |
          cd src
          docker build \
          --tag ghcr.io/${{ steps.repository_name.outputs.lowercase }}/delob:${{ github.ref_name }} \
          .
          docker push ghcr.io/${{ steps.repository_name.outputs.lowercase }}/delob:${{ github.ref_name }}